import numpy
import paddleocr
import skimage
import flask
import flask_cors
import dotenv
import spacy
import transformers
import google.protobuf

print(f"NumPy: {numpy.__version__}")
print(f"PaddleOCR: {paddleocr.__version__}")
print(f"Scikit-image: {skimage.__version__}")
print(f"Flask: {flask.__version__}")
print(f"Flask-CORS: {flask_cors.__version__}")
print(f"python-dotenv: {dotenv.__version__}")
print(f"Spacy: {spacy.__version__}")
print(f"Transformers: {transformers.__version__}")
print(f"Protobuf: {google.protobuf.__version__}")